<?php
/**
 * Created by PhpStorm.
 * User: HP
 * Date: 5/19/2019
 * Time: 9:56 PM
 */

namespace Multiple\Frontend\Controllers;


use Phalcon\Mvc\View;

class CheckoutController extends BaseController
{

    public function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function indexAction(){
        return $this->view->setRenderLevel(View::LEVEL_AFTER_TEMPLATE);
    }
}